services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.4
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=queries_are_fun
    volumes:
      - grafana-storage:/var/lib/grafana
      - '$PWD/apps/grafana/provisioning:/etc/grafana/provisioning'
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.11.0-distroless
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
      - '$PWD/apps/prometheus/:/etc/config'
    command:
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  loki:
    container_name: loki
    image: grafana/loki:3.7.1
    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-target=all"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./apps/loki/config.yaml:/etc/loki/config.yaml
      - loki-storage:/loki
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    container_name: tempo
    image: grafana/tempo:2.10.3
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # OTLP GRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./apps/tempo/config.yaml:/etc/tempo.yaml
      - tempo-storage:/var/tempo
    environment:
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    command:
      - "-config.file=/etc/tempo.yaml"
      - "-target=all"
    restart: always

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  tempo-storage: {}
  loki-storage: {}
