services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.4
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=queries_are_fun
    volumes:
      - grafana-storage:/var/lib/grafana
      - '$PWD/apps/grafana/provisioning:/etc/grafana/provisioning'
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.11.0-distroless
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
      - '$PWD/apps/prometheus/:/etc/config'
    command:
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  tempo:
    container_name: tempo
    image: grafana/tempo:2.10.3
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # OTLP GRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./apps/tempo/config.yaml:/etc/tempo.yaml
      - tempo-storage:/var/tempo
    environment:
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
    command:
      - "-target=all -config.file=/etc/tempo.yaml"
    restart: always

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  tempo-storage: {}
