apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: true
      allowAsRecordingRulesTarget: true
      prometheusType: Prometheus
      prometheusVersion: 3.11.0
      cacheLevel: 'Medium'
      disableRecordingRules: false
      seriesEndpoint: false
      timeInterval: 15s # Prometheus scrape interval
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        customQuery: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    basicAuth: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
